'use client'

import { useState, useEffect, useRef } from 'react'
import Link from 'next/link'
import { ExternalLink } from 'lucide-react'

const projectsData = [
  {
    title: 'DocuForge',
    slug: 'docuforge',
    description: 'Transform your document workflows with DocuForge - the all-in-one solution for document generation, management, and automation. Built for modern businesses that need powerful, yet easy-to-use document handling capabilities.',
    image: 'https://ext.same-assets.com/2113166016/1322219554.png',
    //link: 'https://docuforgeo.netlify.app/'
  },
  {
    title: 'AI Shield Alert',
    slug: 'ai-shield-alert',
    description: 'A comprehensive phishing detection and email security platform that uses artificial intelligence to identify and protect users from sophisticated phishing attempts, including those generated by AI.',
    image: 'https://ext.same-assets.com/2113166016/2934793047.png',
    //link: 'https://ai-shield-alert.netlify.app/'
  },
  {
    title: 'Energy Management Dashboard',
    slug: 'energy-management-dashboard',
    description: 'A comprehensive React dashboard for renewable energy management with interactive charts and real-time monitoring.',
    image: 'https://ext.same-assets.com/2113166016/2589826848.png',
    //link: 'https://astounding-chaja-317f3f.netlify.app/'
  },
  // {
  // title: 'TaskTitan',
  //   slug: 'tasktitan',
  //   description: 'A cross-platform productivity app built using Expo and React Native to help users overcome procrastination.',
  //   image: 'https://ext.same-assets.com/2113166016/870999341.png',
  //   //link: 'https://velvety-kataifi-522d2b.netlify.app/'
  // },
  // {
  //   title: 'BioHackerDepot',
  //   slug: 'project-one',
  //   description: 'Leading platform in the field of biohacking and longevity optimization. Our mission is to provide individuals aged 26-75 with reliable information, resources, and cutting-edge products to enhance their quality of life and well-being.',
  //   image: 'https://ext.same-assets.com/2113166016/1441146841.png',
  //   //link: 'https://biohackerdepot.com/about/'
  // },
  // {
  //   title: 'ClaudsCyberCourse',
  //   slug: 'claudscybercourse',
  //   description: 'An introductory course in cybersecurity designed to equip learners with the essential knowledge and practical skills to safeguard digital systems. The course covers topics such as network security fundamentals, threat analysis, incident response, risk management, and data protection best practices.',
  //   image: 'https://ext.same-assets.com/2113166016/3513841212.png',
  //   //link: 'https://statuesque-beignet-be9d84.netlify.app/'
  // },
  // {
  //   title: 'BioHackMastery',
  //   slug: 'biohackmastery',
  //   description: 'A modern React Native application for tracking and optimizing peptide protocols, wellness metrics, and body composition data.',
  //   image: 'https://ext.same-assets.com/2113166016/2529772715.png',
  //   //link: 'https://biohackmastery.netlify.app/'
  // }
]

export default function Projects() {
  const [isVisible, setIsVisible] = useState(false)
  const sectionRef = useRef<HTMLElement>(null)

  useEffect(() => {
    const currentRef = sectionRef.current
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setIsVisible(true)
          observer.unobserve(entry.target)
        }
      },
      { threshold: 0.2 }
    )

    if (currentRef) {
      observer.observe(currentRef)
    }

    return () => {
      if (currentRef) {
        observer.unobserve(currentRef)
      }
    }
  }, [])

  return (
    <section ref={sectionRef} className="section-padding section-gradient">
      <div className="max-w-7xl mx-auto container-padding">
        <div className={`text-center mb-16 ${isVisible ? 'animate-fadeInUp' : 'opacity-0'}`}>
          <span className="text-purple-400 font-semibold text-sm tracking-wide uppercase"></span>
          <h2 className="heading-lg text-white mt-4 mb-6">
            Featured
            <span className="gradient-text"> Projects</span>
          </h2>
          <p className="text-zinc-400 body-md max-w-2xl mx-auto">
            A showcase of innovative solutions spanning web development and AI automation
          </p>
        </div>

        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
          {projectsData.map((project, index) => (
            <div
              key={project.slug}
              className={`group perspective-1000 ${isVisible ? 'animate-fadeInUp' : 'opacity-0'}`}
              style={{ animationDelay: `${index * 150}ms` }}
            >
              <div className="relative preserve-3d card-hover">
                <div className="glass rounded-2xl overflow-hidden">
                  {/* Project Image */}
                  <div className="relative overflow-hidden bg-zinc-800/50">
                    <img
                      src={project.image}
                      alt={project.title}
                      className="w-full h-48 object-cover group-hover:scale-110 transition-transform duration-500"
                    />
                    <div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300" />
                  </div>

                  {/* Project Content */}
                  <div className="p-6 space-y-4">
                    <h3 className="text-xl font-semibold text-white group-hover:text-purple-400 transition-colors">
                      {project.title}
                    </h3>
                    <p className="text-zinc-400 text-sm leading-relaxed line-clamp-3">
                      {project.description}
                    </p>

                    {/* Action Buttons */}
                    <div className="flex items-center justify-between pt-4">
                      {/* <Link
                        href={`/summary/${project.slug}`}
                        className="group/btn inline-flex items-center space-x-2 px-4 py-2 bg-zinc-800 hover:bg-zinc-700 rounded-lg text-sm font-medium text-zinc-300 hover:text-white transition-all duration-300 focus-ring"
                      >
                        <span>Summary</span>
                        <ExternalLink className="w-3 h-3 group-hover/btn:translate-x-0.5 transition-transform" />
                      </Link> */}

                      {/* {project.link && (
                        <a
                          href={project.link}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="group/btn inline-flex items-center space-x-2 px-4 py-2 bg-gradient-to-r from-purple-500 to-violet-500 rounded-lg text-sm font-medium text-white magnetic hover:scale-105 transition-all duration-300 glow-hover focus-ring"
                        >
                          <span>Live Demo</span>
                          <ExternalLink className="w-3 h-3 group-hover/btn:translate-x-0.5 transition-transform" />
                        </a>
                      )} */}
                    </div>
                  </div>

                  {/* Hover Overlay */}
                  <div className="absolute inset-0 bg-gradient-to-br from-purple-500/5 to-violet-500/5 opacity-0 group-hover:opacity-100 transition-opacity duration-300 pointer-events-none" />
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  )
}
